codecov:
    token: 0989df3c-1c7e-4011-818e-e98ca33b1241
    require_ci_to_pass: yes
    max_report_age: off

coverage:
    precision: 2
    round: down
    range: "70...100"
    
fixes:
    - "src/::"
