on: ['push', 'pull_request']
jobs:
  osx_mdp_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Setup
      run: pip install .
    - name: Run tests
      run: |
        python testing/overcooked_test.py
        python testing/planners_test.py

  ubuntu_mdp_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Setup
      run: pip install .
    - name: Run tests
      run: |
        python testing/overcooked_test.py
        python testing/planners_test.py
